package calculadorarpc;

import java.util.Vector;
import org.apache.xmlrpc.XmlRpcClient;

/**
 *
 * @author papg864
 */

public class InterfazCalculadora extends javax.swing.JFrame {

     
    public InterfazCalculadora() {
        initComponents();
        setResizable(false);
        setTitle("Calculadora RPC");
        setLocationRelativeTo(null);
        textFocus = valor1TXT;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        resultadoTXT = new javax.swing.JTextField();
        comaBTN = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        buttonCE = new javax.swing.JButton();
        sumaBTN = new javax.swing.JButton();
        restaBTN = new javax.swing.JButton();
        multiplicacionBTN = new javax.swing.JButton();
        divisionBTN = new javax.swing.JButton();
        valor1TXT = new javax.swing.JTextField();
        ceroBTN = new javax.swing.JButton();
        valor2TXT = new javax.swing.JTextField();
        operadorLB = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        unoBTN = new javax.swing.JButton();
        dosBTN = new javax.swing.JButton();
        tresBTN = new javax.swing.JButton();
        cuatroBTN = new javax.swing.JButton();
        cincoBTN = new javax.swing.JButton();
        seisBTN = new javax.swing.JButton();
        sieteBTN = new javax.swing.JButton();
        ochoBTN = new javax.swing.JButton();
        nueveBTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        resultadoTXT.setEditable(false);
        resultadoTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoTXTActionPerformed(evt);
            }
        });

        comaBTN.setText(".");
        comaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comaBTNActionPerformed(evt);
            }
        });

        jLabel3.setText("=");

        buttonCE.setText("<-");
        buttonCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCEActionPerformed(evt);
            }
        });

        sumaBTN.setText("+");
        sumaBTN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sumaBTNFocusGained(evt);
            }
        });
        sumaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaBTNActionPerformed(evt);
            }
        });

        restaBTN.setText("-");
        restaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaBTNActionPerformed(evt);
            }
        });

        multiplicacionBTN.setText("×");
        multiplicacionBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicacionBTNActionPerformed(evt);
            }
        });

        divisionBTN.setText("÷");
        divisionBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionBTNActionPerformed(evt);
            }
        });

        valor1TXT.setEditable(false);
        valor1TXT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                valor1TXTFocusGained(evt);
            }
        });
        valor1TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor1TXTActionPerformed(evt);
            }
        });

        ceroBTN.setText("0");
        ceroBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroBTNActionPerformed(evt);
            }
        });

        valor2TXT.setEditable(false);
        valor2TXT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                valor2TXTFocusGained(evt);
            }
        });
        valor2TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor2TXTActionPerformed(evt);
            }
        });

        jLabel1.setText("CALCULADORA XML-RPC");

        unoBTN.setText("1");
        unoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoBTNActionPerformed(evt);
            }
        });

        dosBTN.setText("2");
        dosBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosBTNActionPerformed(evt);
            }
        });

        tresBTN.setText("3");
        tresBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresBTNActionPerformed(evt);
            }
        });

        cuatroBTN.setText("4");
        cuatroBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroBTNActionPerformed(evt);
            }
        });

        cincoBTN.setText("5");
        cincoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoBTNActionPerformed(evt);
            }
        });

        seisBTN.setText("6");
        seisBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisBTNActionPerformed(evt);
            }
        });

        sieteBTN.setText("7");
        sieteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sieteBTNActionPerformed(evt);
            }
        });

        ochoBTN.setText("8");
        ochoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoBTNActionPerformed(evt);
            }
        });

        nueveBTN.setText("9");
        nueveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueveBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cincoBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seisBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ceroBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nueveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comaBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonCE, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sieteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ochoBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(valor1TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(operadorLB)
                                .addGap(5, 5, 5)
                                .addComponent(valor2TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel3)
                                .addGap(5, 5, 5)
                                .addComponent(resultadoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(unoBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                                    .addComponent(sumaBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(restaBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(multiplicacionBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(divisionBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(dosBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tresBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cuatroBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(13, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(resultadoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(valor1TXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(operadorLB)
                        .addComponent(valor2TXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sumaBTN)
                    .addComponent(restaBTN)
                    .addComponent(multiplicacionBTN)
                    .addComponent(divisionBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unoBTN)
                    .addComponent(dosBTN)
                    .addComponent(tresBTN)
                    .addComponent(cuatroBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cincoBTN)
                    .addComponent(seisBTN)
                    .addComponent(sieteBTN)
                    .addComponent(ochoBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ceroBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comaBTN)
                    .addComponent(buttonCE)
                    .addComponent(nueveBTN))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jLabel2.setText("Ingrese los Digitos primero");

        jLabel4.setText("Para luego Ingresar el ");

        jLabel5.setText("Operador y obtener el");

        jLabel6.setText("resultado.");

        jLabel7.setText("En este caso el servidor");

        jLabel8.setText("realizara el procedimiento de ");

        jLabel9.setText("las Operaciones.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(54, 54, 54)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ochoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ochoBTNActionPerformed
        textFocus.setText(textFocus.getText() + "8");
    }//GEN-LAST:event_ochoBTNActionPerformed

    private void nueveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueveBTNActionPerformed
        textFocus.setText(textFocus.getText() + "9");
    }//GEN-LAST:event_nueveBTNActionPerformed

    private void resultadoTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoTXTActionPerformed

    private void comaBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comaBTNActionPerformed
        if(!(textFocus.getText().contains(".") || textFocus.getText().equals("")))
        textFocus.setText(textFocus.getText() + ".");
    }//GEN-LAST:event_comaBTNActionPerformed

    private void buttonCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCEActionPerformed
        valor1TXT.setText("");
        valor2TXT.setText("");
        resultadoTXT.setText("");
        operadorLB.setText("");
    }//GEN-LAST:event_buttonCEActionPerformed

    private void sumaBTNFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sumaBTNFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_sumaBTNFocusGained

    private void sumaBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaBTNActionPerformed
        operadorLB.setText("+");
        operacion("sum");
    }//GEN-LAST:event_sumaBTNActionPerformed

    private void restaBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaBTNActionPerformed
        operadorLB.setText("-");
        operacion("rest");
    }//GEN-LAST:event_restaBTNActionPerformed

    private void multiplicacionBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicacionBTNActionPerformed
        operadorLB.setText("×");
        operacion("mul");
    }//GEN-LAST:event_multiplicacionBTNActionPerformed

    private void divisionBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionBTNActionPerformed
        operadorLB.setText("÷");
        operacion("div");
    }//GEN-LAST:event_divisionBTNActionPerformed

    private void valor1TXTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valor1TXTFocusGained
        textFocus = valor1TXT;
    }//GEN-LAST:event_valor1TXTFocusGained

    private void valor1TXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor1TXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valor1TXTActionPerformed

    private void ceroBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceroBTNActionPerformed
        if(!textFocus.getText().equals("0"))
        textFocus.setText(textFocus.getText() + "0");

    }//GEN-LAST:event_ceroBTNActionPerformed

    private void dosBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosBTNActionPerformed
        textFocus.setText(textFocus.getText() + "2");
    }//GEN-LAST:event_dosBTNActionPerformed

    private void unoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoBTNActionPerformed
        textFocus.setText(textFocus.getText() + "1");
    }//GEN-LAST:event_unoBTNActionPerformed

    private void tresBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresBTNActionPerformed
        textFocus.setText(textFocus.getText() + "3");
    }//GEN-LAST:event_tresBTNActionPerformed

    private void cuatroBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroBTNActionPerformed
        textFocus.setText(textFocus.getText() + "4");
    }//GEN-LAST:event_cuatroBTNActionPerformed

    private void seisBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisBTNActionPerformed
        textFocus.setText(textFocus.getText() + "6");
    }//GEN-LAST:event_seisBTNActionPerformed

    private void cincoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoBTNActionPerformed
        textFocus.setText(textFocus.getText() + "5");
    }//GEN-LAST:event_cincoBTNActionPerformed

    private void valor2TXTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valor2TXTFocusGained
        textFocus = valor2TXT;
    }//GEN-LAST:event_valor2TXTFocusGained

    private void valor2TXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor2TXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valor2TXTActionPerformed

    private void sieteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sieteBTNActionPerformed
        textFocus.setText(textFocus.getText() + "7");
    }//GEN-LAST:event_sieteBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCE;
    private javax.swing.JButton ceroBTN;
    private javax.swing.JButton cincoBTN;
    private javax.swing.JButton comaBTN;
    private javax.swing.JButton cuatroBTN;
    private javax.swing.JButton divisionBTN;
    private javax.swing.JButton dosBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton multiplicacionBTN;
    private javax.swing.JButton nueveBTN;
    private javax.swing.JButton ochoBTN;
    private javax.swing.JLabel operadorLB;
    private javax.swing.JButton restaBTN;
    private javax.swing.JTextField resultadoTXT;
    private javax.swing.JButton seisBTN;
    private javax.swing.JButton sieteBTN;
    private javax.swing.JButton sumaBTN;
    private javax.swing.JButton tresBTN;
    private javax.swing.JButton unoBTN;
    private javax.swing.JTextField valor1TXT;
    private javax.swing.JTextField valor2TXT;
    // End of variables declaration//GEN-END:variables


     private javax.swing.JTextField textFocus;
     
 public void operacion (String op){ 
        try {
         
            XmlRpcClient servidor = new XmlRpcClient("http://localhost:1024/RPC2"); 
         
         
            Vector parametros = new Vector();
         
         
            parametros.addElement(Double.parseDouble(valor1TXT.getText()));
         
            parametros.addElement(Double.parseDouble(valor2TXT.getText()));
         
            Object resultado = servidor.execute("sample." + op, parametros);
         
            resultadoTXT.setText(((Double) resultado).doubleValue()+"");

        } catch (Exception exception) {
        System.err.println("JavaClient: " + exception);
        }
}
 
}
